# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDLq8YAcQz--2Ltn0gKnMN_BbMUtJFsy
"""

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/MatheusFreitag/SACOMP_2019/master/data/cannabis.csv')

df.head()

df

sorted(df['Rating'].unique())

plt.hist(df['Rating'].values, bins=10)

df['Rating'].value_counts().sort_values(ascending=True)

df[df['Rating']>4].loc[:, ['Effects', 'Flavor']]

dict_of_effects = dict()

for list_of_effects in df[df['Rating'] > 4].loc[:, 'Effects'].values:
  for effect in list_of_effects.split(','):
    if effect in dict_of_effects.keys():
      dict_of_effects[effect] += 1
    else:
      dict_of_effects[effect] = 1

pd.DataFrame.from_dict(dict_of_effects, orient='index', columns=['count']).sort_values(by='count', ascending=False)

dict_of_effects = dict()

for list_of_effects in df[df['Rating'] < 3].loc[:, 'Effects'].values:
  for effect in list_of_effects.split(','):
    if effect in dict_of_effects.keys():
      dict_of_effects[effect] += 1
    else:
      dict_of_effects[effect] = 1

pd.DataFrame.from_dict(dict_of_effects, orient='index', columns=['count']).sort_values(by='count', ascending=False)

dict_of_flavors = dict()

for list_of_flavors in df[df['Rating'] < 3].loc[:, 'Flavor'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

set_low_rate_flavors = set(dict_of_flavors.keys())
pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

dict_of_flavors = dict()

for list_of_flavors in df[df['Rating'] > 4].loc[:, 'Flavor'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

set_high_rate_flavors = set(dict_of_flavors.keys())
pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

set_high_rate_flavors.difference(set_low_rate_flavors)

set_low_rate_flavors.difference(set_high_rate_flavors)

set_high_rate_flavors.intersection(set_low_rate_flavors)

df[df['Rating'] > 4].loc[:, 'Type'].value_counts()

df[df['Rating'] < 3].loc[:, 'Type'].value_counts()

dict_of_flavors = dict()

for list_of_flavors in df[df['Type'] == 'indica'].loc[:, 'Flavor'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

Saboresindica = pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

dict_of_flavors = dict()

for list_of_flavors in df[df['Type'] == 'sativa'].loc[:, 'Flavor'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

Saboressativa = pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

Saboresindica

Saboressativa

dict_of_flavors = dict()

for list_of_flavors in df[df['Type'] == 'indica'].loc[:, 'Effects'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

Efeitosindica = pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

dict_of_flavors = dict()

for list_of_flavors in df[df['Type'] == 'sativa'].loc[:, 'Effects'].astype(str).values:
    # if type(list_of_flavors) == str:
    for flavor in list_of_flavors.split(','):
      if flavor in dict_of_flavors.keys():
        dict_of_flavors[flavor] += 1
      else:
        dict_of_flavors[flavor] = 1

Efeitossativa = pd.DataFrame.from_dict(dict_of_flavors, orient='index', columns=['count']).sort_values(by='count', ascending=False)

Efeitosindica

Efeitossativa

